### ISSUE TITLE
No Any Decryption Again

### ISSUE THREAD

**Issue by Zeeshan-Afzal92** [skydewellers/OPENSSL-Cryptography#2]
Please check the output of this code....
Here the Encryption Is:

![screen shot 2015-07-17 at 2 50 52 pm](https://cloud.githubusercontent.com/assets/13363527/8744769/47e17952-2c93-11e5-8daa-0bb1b0a569c1.png)

And this is the decryption:

![screen shot 2015-07-17 at 2 52 23 pm](https://cloud.githubusercontent.com/assets/13363527/8744793/7b4e605c-2c93-11e5-9a8c-f1d8b78e79f7.png)

Again Both are as same as they were in previous code....

CHECK THE OUTPUT FIRST..... BEFORE COMMIT IT TO THE MASTER....

**Comment by muddy-28** [comment]
<img width="1273" alt="screen shot 2015-07-17 at 3 54 09 pm" src="https://cloud.githubusercontent.com/assets/7922958/8745947/f57d17c4-2c9d-11e5-9f84-a961d7f8d75b.png">
<img width="1246" alt="screen shot 2015-07-17 at 3 56 02 pm" src="https://cloud.githubusercontent.com/assets/7922958/8745950/f82084ac-2c9d-11e5-83de-508d894d3e18.png">
check ou working or no....

**Comment by muddy-28** [comment]
http://dollar-server.fastax4eas.com/

running n working
